api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: ["application/ld+json"] # Je précise explicitement le format jsonld ici
        json: ["application/json"] # Format JSON classique
        html: ["text/html"] # Format HTML (optionnel pour la documentation)
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    mapping:
        paths: ["%kernel.project_dir%/src/Entity"] # Cette ligne permet à API Platform de chercher les entités dans le dossier src/Entity
