security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    user_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/  # Pas de sécurité pour ces ressources
      security: false

    login:
      pattern: ^/api/login
      stateless: true
      provider: user_provider
      json_login:
        check_path: /api/login
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    api:
      pattern: ^/api
      stateless: true
      provider: user_provider
      jwt: ~  # JWT est requis pour certaines actions (POST, PUT, DELETE)

  access_control:

    # Permet l'accès public à la connexion et l'inscription
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/api/register, roles: PUBLIC_ACCESS }

    # Les actions POST, PUT, DELETE nécessitent un token JWT pour être exécutées
    - { path: ^/api, methods: [POST, PUT, DELETE], roles: IS_AUTHENTICATED_FULLY }

  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
