services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: jobyfind-app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - jobyfind-network

    nginx:
        image: nginx:alpine
        container_name: jobyfind-nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - jobyfind-network

    db:
        image: mysql:8.0
        container_name: jobyfind-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: jobyfind
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - jobyfind-network

    test_db:
        image: mysql:8.0
        container_name: jobyfind-test-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: jobyfind_test
        ports:
            - "3307:3306"
        networks:
            - jobyfind-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: jobyfind-phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"
        networks:
            - jobyfind-network

    phpmyadmin_test:
        image: phpmyadmin/phpmyadmin
        container_name: jobyfind-phpmyadmin-test
        environment:
            PMA_HOST: test_db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
        networks:
            - jobyfind-network

networks:
    jobyfind-network:
        driver: bridge

volumes:
    db_data:
