# fly.toml app configuration file generated for jobyfind-api on 2025-06-10T21:20:41+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jobyfind-api'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile.prod'

[env]
  APP_DEBUG = 'false'
  APP_ENV = 'prod'
  PHP_OPCACHE_ENABLE = '1'

[processes]
  web = 'apache2-foreground'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['web']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/api/health'
    protocol = 'http'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[statics]]
  guest_path = '/var/www/html/public'
  url_prefix = '/static/'
